language: csharp
solution: SKON.NET/SKON.NET.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore SKON.NET/SKON.NET.sln
after_script:
  - nunit-console SKON.NET/UnitTests/bin/Release/UnitTests.dll